### PR TITLE
Lexeme fixes from arXMLiv 2020

### LINKED ISSUE #1465: Further lexeme upgrades
An issue to collect lexeme upgrades for the next time we rerun arXiv, if I may.
One unfortunate observation is that the current code lexes `\underline{A}` and `\overline{A}` the same, namely as:

```
¯ start_ARG italic_A end_ARG
```

They ought to be distinct, and there may be a better syntax. Maybe:
```
¯ overarg start_ARG italic_A end_ARG
¯ underarg start_ARG italic_A end_ARG
```

### PR DESCRIPTION
**Pull request by dginev**
Fixes #1465 .

Addresses the two easy+obvious cases in the issue, deferring more advanced problems (long annotations, color lexemes) for 2022.

This should be all that's needed for the arXMLiv 2021 rerun, lexeme-wise.

### CODE REVIEW

File: lib/LaTeXML/MathParser.pm [hunk 1]
```diff
@@ -714,7 +714,10 @@ sub node_to_lexeme {
           if (my $value = $$properties_pending{$attr}) {
             push @to_add, $value; } }
```
Comment (brucemiller) [inline lib/LaTeXML/MathParser.pm:715]: Wouldn't it have been simpler to simply make `@to_add` a hash in the first place, and then `$to_add{$value}=1;` and use `keys %to_add` later ?

Comment (dginev) [reply lib/LaTeXML/MathParser.pm:715]: sure, can do!

**Comment by brucemiller** [comment]
cool; thanks!
