### PR TITLE
Integrate logs from separate bibliography converts in post-processing

### LINKED ISSUE #916: Postprocessing doesn't show errors during processing of bibliography
When processing the bibliography `latexmlpost` only shows the number of errors encountered, but doesn't give any hint, what went wrong:

```
latexmlpost --verbose --verbose --verbose --dest=equations.html equations.xml 

(MakeBibliography equations.html processing... [Converting bibliography equations/test.bib ...


Conversion complete: 1 error.
Status:conversion:2 
... converted!] [using bibliographies test.bib] [154 bibentries, 9 cited] [DBStatus: 8195/0 objects] 13.45 sec)
```
With a big `*.bib` file, it can be quite painful to track down these errors. It would be nice, if `latexmlpost` would at least give the line number, where it encountered problems parsing or processing the `*.bib` file.

### PR DESCRIPTION
**Pull request by dginev**
Fixes #916 

A bit tricky, since managing the STDERR redirects is getting wild, but it works nicely. Unsure about the final log to print, attaching screenshots with this version. I did not want to indent the messages, so that automated regexes (e.g. from cortex) can still parse the log as usual.

Here are the logs converting the the issue example, with `master`:

master

And the logs after this PR is installed:

new

### CODE REVIEW

File: lib/LaTeXML.pm [hunk 1]
```diff
@@ -255,7 +256,6 @@ sub convert {
       my ($state) = @_;    # Remove current state frame
       $$opts{searchpaths} = $state->lookupValue('SEARCHPATHS'); # save the searchpaths for post-processing
       $state->popDaemonFrame;
-      $$state{status} = {};
```
Comment (dginev) [inline lib/LaTeXML.pm]: this was the only place I had to touch the actual daemon core logic.

In essence, instead of immediately reset-ing the status hash after a conversion run is completed, I now reset it before a fresh run is started. This way I can still reuse the hash for passing on the log to a parent converter object.

File: lib/LaTeXML/Common/Error.pm [hunk 2]
```diff
@@ -357,11 +357,9 @@ sub MergeStatus {
     if ($type eq 'undefined' or $type eq 'missing') {
       my $table = $$external_status{$type};
       foreach my $subtype(keys %$table) {
-        $$status{$type}{$subtype} ||= 0;
         $$status{$type}{$subtype} += $$table{$subtype};
       }
     } else {
-      $$status{$type} ||= 0;
```
Comment (dginev) [inline lib/LaTeXML/Common/Error.pm]: I have gotten used to being extra cautious from my Ruby days, let me know if you want these guards back @brucemiller

Comment (dginev) [reply lib/LaTeXML/Common/Error.pm]: works just fine without them naturally

**Comment by brucemiller** [comment]
Looks good; let me know when you're done :>

**Comment by dginev** [comment]
Oh, i am done here.

**Comment by brucemiller** [comment]
Cool! Thanks!!
